namespace Rosalia.TaskLib.AssemblyInfo.Tests
{
    using System.Reflection;
    using NUnit.Framework;
    using Rosalia.Core;
    using Rosalia.Core.Tests;
    using Rosalia.Core.Tests.Stubs;

    public class GenerateAssemblyInfoTaskTests : TaskTestsBase
    {
        [Test]
        public void Execute_ValidInput_ShouldGenerateOutput()
        {
            var destination = new FileStub();
            var task = new GenerateAssemblyInfo()
                .WithAttribute(_ => new AssemblyVersionAttribute("1.0.42"))
                .WithAttribute(_ => new AssemblyCompanyAttribute("Starfuckers, Inc."))
                .ToFile(destination);

            var context = CreateContext();


            var result = context.Executer.Execute(task);

            Assert.That(result.ResultType, Is.EqualTo(ResultType.Success));

            Assert.That(destination.Content.Trim(), Is.EqualTo(
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersionAttribute(""1.0.42"")]
[assembly: AssemblyCompanyAttribute(""Starfuckers, Inc."")]"));
        }
    }
}