namespace Rosalia.TaskLib.AssemblyInfo.Tests
{
    using System.Reflection;
    using NUnit.Framework;
    using Rosalia.Core.Tests;
    using Rosalia.Core.Tests.Stubs;

    public class GenerateAssemblyInfoTaskTests : TaskTestsBase<GenerateAssemblyInfoTaskTests.Context>
    {
        [Test]
        public void Execute_ValidInput_ShouldGenerateOutput()
        {
            var destination = new FileStub();
            var task = new GenerateAssemblyInfo<Context>()
                .WithAttribute(c => new AssemblyVersionAttribute(c.VersionNumber))
                .WithAttribute(c => new AssemblyCompanyAttribute(c.CompanyName))
                .ToFile(destination);

            var context = CreateContext();

            context.Data.VersionNumber = "1.0.42";
            context.Data.CompanyName = "Starfuckers, Inc.";

            context.Executer.Execute(task);

            Assert.That(destination.Content.Trim(), Is.EqualTo(
@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyVersionAttribute(""1.0.42"")]
[assembly: AssemblyCompanyAttribute(""Starfuckers, Inc."")]"));
        }

        public class Context
        {
            public string VersionNumber { get; set; }

            public string CompanyName { get; set; }
        }
    }
}