//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyProductAttribute("Rosalia")]
[assembly: AssemblyVersionAttribute("2.6.14")]
[assembly: AssemblyFileVersionAttribute("2.6.14")]
